resources/building-mobile-extensions/building-an-extension.md
resources/building-mobile-extensions/clearing-a-shared-state.md
resources/building-mobile-extensions/dispatching-events-from-your-extension.md
resources/building-mobile-extensions/event-listeners.md
resources/building-mobile-extensions/monitoring-shared-states.md
resources/building-mobile-extensions/requesting-a-shared-state-that-is-not-tied-to-an-event.md
resources/building-mobile-extensions/requesting-a-shared-state.md
resources/building-mobile-extensions/updating-a-shared-state-that-is-not-tied-to-an-event.md
resources/building-mobile-extensions/updating-the-shared-state.md
using-mobile-extensions/mobile-core/configuration-reference/rules-engine-reference.md

Changes:
- Updated extension registration error handling section in Android
- Added tabs in the Build your own extension section for ios/android code examples
- Renamed Adobe Cloud Platform SDK to Adobe Experience Platform SDK

[AMSDK-7323] Updated extension registration error handling section and added tabs for ios/android code

---

using-mobile-extensions/mobile-core/mobile-core-api-reference.md

Initial add of new Logging APIs to mobile core api reference page.
NOTE: PR adds changes to `core-logging-apis branch`

adding logging API to mobile core api reference

---

using-mobile-extensions/mobile-core/mobile-core-api-reference.md

Logging APIs for Android changed to use single `log` method. Update MobileCore API reference to reflect change.

change Android Logging API to single log method

---

using-mobile-extensions/adobe-analytics/README.md

We're adding info to the tooltips for trackAction and trackState for Rules action configuration, so we want this info reflected in the documentation as well.

Updating Analytics docs with some more info on trackAction and trackState

---

using-mobile-extensions/mobile-core/identity/identity-api-reference.md
using-mobile-extensions/mobile-core/identity/identity-event-reference.md

Clean up work for the Identity Extension core code.
- Remove reference to `vid` in Identity shared state, as it wasn't being set previously and is now removed from the code
- List Analytics Tracking ID as being set in appendToUrl/appendVisitorInfoForUrl

[AMSDK-7030] Remove vid from Identity

---

release-notes.md

update release notes for iOS 2.2.2 Andorid 1.3.1 with fix for getPrivacyStatus when device is offline

Update to release notes for iOS 2.2.2 and Android 1.3.1

---

using-mobile-extensions/mobile-core/identity/README.md
using-mobile-extensions/mobile-core/identity/identity-api-reference.md

Add API reference for Identity.getUrlVariables on React Native platform.
Add "Visitor Tracking Between an App and Mobile Web" section in Identity.

Add Identity getUrlVariables API reference for React Native platform

---

using-mobile-extensions/mobile-core/identity/identity-api-reference.md

Clarify the Identity.appendToURL API to state the Adobe visitor information is appended to the query component of the given URL.

[AMSDK-8575] Clarify Identity.appendToURL API

---

using-mobile-extensions/mobile-core/identity/identity-api-reference.md

1. Use code fences in info hint for Identity.appendVisitorInfoForUrl to allow horizontal scrolling of text.
2. Moved hint to bottom of card to improve reading flow.
3. Add another example of how the visitor data is appended to a URL.

Cleanup hint on Identity.appendVisitorInfoForUrl API reference

---

SUMMARY.md

Add launch-data-elements page to TOC as 'Using data elements to define dynamic data in rules' under Tutorials

Update TOC with data elements tutorial.

---

getting-started/create-a-mobile-property.md

Little confusing to know where the list of properties described is at unless you save first. Some customers were missing that step.

Add step to save mobile property

---

using-mobile-extensions/mobile-core/identity/identity-api-reference.md

Add new APIs to Identity for release v2.2.0 (Core v2.5.0).
New APIs include:
- appendToURL:withCompletionHandler
- getUrlVariablesWithCompletionHandler
- getIdentifiersWithCompletionHandler
- getExperienceCloudIdWithCompletionHandler

Add new completionHandler APIs to identity-api-reference.md

---

beta/project-griffon/set-up-project-griffon/README.md
beta/project-griffon/set-up-project-griffon/project-griffon-sdk-api-reference.md
using-mobile-extensions/adobe-analytics/README.md
using-mobile-extensions/mobile-core/configuration/README.md
using-mobile-extensions/mobile-core/identity/README.md
using-mobile-extensions/mobile-core/lifecycle/README.md
using-mobile-extensions/mobile-core/lifecycle/lifecycle-api-reference.md
using-mobile-extensions/mobile-core/signals/README.md

- also add docs for cordova griffon.
- add information regarding which AEP SDK API must be called natively.

Update cordova AEP SDK doc readme files

---

resources/upgrading-to-aep/current-sdk-versions.md

Link was pointing to an old tagged version. Updated to the base folder instead.

Update link for GitHub for iOS Griffon

---

using-mobile-extensions/mobile-core/platform-services.md

- Formatting and added tabs for iOS&Android
- Add imports/includes required for these examples
- Add obj-c example for creating NSURLSessionConfiguration and NSMutableURLRequest

Update obj-c&Android samples for network service overrider

---

beta/project-griffon/set-up-project-griffon/README.md
using-mobile-extensions/mobile-core/lifecycle/README.md

With iOS 13, Apple introduced [Scenes](https://developer.apple.com/documentation/uikit/app_and_environment/scenes?language=objc) which affects the hooks for the application lifecycle. If an app is using Scenes, the `UISceneDelegate` is used for certain lifecycle hooks instead of the `AppDelegate`. In order to clarify our lifecycle documentation as well as the Griffon `startSession` documentation, we have added some example code to support Scenes.

UISceneDelegate iOS 13 documentation for LifeCycle and Griffon

---

beta/project-griffon/set-up-project-griffon/README.md
beta/project-griffon/set-up-project-griffon/project-griffon-sdk-api-reference.md
getting-started/enable-lifecycle-metrics.md
getting-started/get-the-sdk.md
getting-started/initialize-the-sdk.md
using-mobile-extensions/adobe-analytics/README.md
using-mobile-extensions/adobe-analytics/analytics-api-reference.md
using-mobile-extensions/mobile-core/configuration/README.md
using-mobile-extensions/mobile-core/configuration/configuration-api-reference.md
using-mobile-extensions/mobile-core/identity/README.md
using-mobile-extensions/mobile-core/identity/identity-api-reference.md
using-mobile-extensions/mobile-core/lifecycle/README.md
using-mobile-extensions/mobile-core/lifecycle/lifecycle-api-reference.md
using-mobile-extensions/mobile-core/mobile-core-api-reference.md
using-mobile-extensions/mobile-core/signals/README.md
using-mobile-extensions/mobile-core/signals/signal-api-reference.md

- update xamarin code samples to use `csharp` code type
- cleanup some confusing code samples
- add missing samples in the "getting started" section
- fix hint formatting issue in the lifecycle README

clean up xamarin docs

---

using-mobile-extensions/mobile-core/lifecycle/README.md

Expected:
``` csharp
public override void DidEnterBackground(UIApplication uiApplication)
{
base.DidEnterBackground(uiApplication);
ACPCore.LifecyclePause();
}
```
Current:
``` csharp
public override void DidEnterBackground(UIApplication uiApplication)
{
base.DidEnterBackground(uiApplication);
ACPCore.LifecycleStart(null);
}
```

Lifecycle event correction.

---

using-mobile-extensions/mobile-core/identity/identity-api-reference.md

Add AppTrackingTransparency example to Identity setAdvertisingIdentifier().
In iOS 14, the existing ASIdentifierManger.isAdvertisingTrackingEnabled is deprecated and is replaced by the AppTrackingTransparency framework. As we currently have a code example on how to get the advertising identifier using ASIdentifierManager, I'm adding an example on using AppTrackingTransparency for app running on iOS 14.

Add AppTrackingTransparency example to Identity docs

---

SUMMARY.md
foundation-extensions/places/migration-v2.md
resources/migrate-to-swift.md

For the moment I created a new migration guide so we can compare with the original and decide which one do we prefer more. Looking fw for your feedback
The main changes are:
- separates Swift and Objective-C instructions
- using AEP (3.x) / AEP (2.x) as tab names
- use sample code examples instead of API syntax examples

Migration guide for Places - swift, objc sections

---

release-notes/README.md
using-mobile-extensions/adobe-target/adobe-target-release-notes.md
using-mobile-extensions/adobe-target/target-api-reference.md

Added docs for the following support:
- Allow reading response tokens and Analytics for Target (A4T) payload in API response

Updated Target docs and release notes 

---

using-mobile-extensions/adobe-analytics-mobile-services/README.md

Fix AEPMobileServices.trackAdobeDeepLink Swift examples plus include examples using SceneDelegate in iOS 13+

Fix Swift code examples for MobileServices trackAdobeDeepLink

---

foundation-extensions/consent-for-edge-network/README.md
foundation-extensions/identity-for-edge-network/README.md

Updates Identity for Edge Network and Consent for Edge Network install instructions with standard iOS tab names for "AEP (3.x)" and "ACP (2.x)".
Removes use of wildcard when importing Android packages.

Update tab names in Edge Identity and Consent install instructions.

---

foundation-extensions/mobile-core/identity/identity-api-reference.md
foundation-extensions/mobile-core/identity/identity-event-reference.md

Fix some broken links after recent changes to Identity docs. Apparently Git Book requires file extension in the URL.

Fix broken links in Identity docs.

---

foundation-extensions/mobile-core/identity/identity-api-reference.md

- Removes unused/unneeded HTML style anchors. These anchors didn't work as Git Book only links to headers, and not normal text
- Change links to `#public-classes` as needed, instead of linking to tabs within Public Classes section.

Fix a few more broken links in Identity docs

---

foundation-extensions/mobile-core/identity/identity-api-reference.md

While investigating an issue for a customer, I was informed by @emdobrin that, "the id type value is cleaned up internally from any of the disallowed characters, the allowed characters are [A-Za-z0-9_.]" 
https://adobedx.slack.com/archives/C02L32RP998/p1641312482315700

Added input restrictions

---

foundation-extensions/mobile-core/configuration/README.md
foundation-extensions/mobile-core/configuration/configuration-api-reference.md

Adds public documentation for the new public API `clearUpdatedConfiguration()` in Android

clearUpdatedConfiguration() API Android syntax and examples

---

foundation-extensions/consent-for-edge-network/release-notes-1.md
foundation-extensions/experience-platform-extension/release-notes.md
foundation-extensions/mobile-core/mobile-core-release-notes.md
release-notes/README.md

Release notes for:
- iOS AEPCore 3.5.0
- iOS AEPEdge 1.4.0
- iOS AEPEdgeConsent 1.0.1

Release notes for iOS AEP Core v3.5.0, Edge v1.4.0, Consent v1.0.1

---

foundation-extensions/consent-for-edge-network/README.md
foundation-extensions/identity-for-edge-network/README.md
foundation-extensions/identity-for-edge-network/api-reference.md

This PR updates the Identity for Edge Network extension's: 
Homepage:
- Update samples to include Consent extension
API documentation to include `setAdvertisingIdentifier`:
- Examples for Android (Java and Kotlin) and iOS (Swift and Obj-C), using the API documentation from the Identity Edge repos as the base. 
See [MOB-16626](https://jira.corp.adobe.com/browse/MOB-16626) for additional task details.

Edge identity set advertising identitfier api update

---

foundation-extensions/mobile-core/rules-engine/README.md

Support for bundled rules has been added from Android sdk-core v1.11.2. Updated the documentation for bundled rules to add details about file placement for Android.

Update Bundled Rules docs to include Android details

---

foundation-extensions/mobile-core/identity/identity-api-reference.md

The current examples for Identity appendToUrl API are not correct. The correct format is `adobe_mc = TS=XXXXXX|MCMID=XXXXXX|MCAID=XXXXXX|MCORGID=XXXXXX@AdobeOrg` as an URL encoded string.

Correct examples for Identity appendToUrl
