Adobe-Marketing-Cloud/aep-sdks-documentation

using-mobile-extensions/profile/README.md, using-mobile-extensions/profile/profile-api-references.md, using-mobile-extensions/profile/profiles-event-reference.md
send update again, it got overwritten
=> AMSDK-6958 send update again

using-mobile-extensions/mobile-core/identity/identity-api-reference.md
There were a few broken links on the Identity page, this PR fixes them.
=> Fix identity links

using-mobile-extensions/adobe-campaignclassic/README.md, using-mobile-extensions/adobe-target/README.md
Update README for target and ACC for static library change
=> Update target and campaignclassic doc for static library change

using-mobile-extensions/adobe-analytics/README.md
=> Add call to core, fix indents

release-notes.md
Same note as March 7th, but new version.
=> Release notes for fix today.

SUMMARY.md, resources/building-mobile-extensions/get-the-application-context.md, using-mobile-extensions/mobile-core/mobile-core-api-reference.md
Add Mobile Core getApplication/setApplication API references
Adding page to "Using Mobile Extensions" on how to get the application context.
=> Get Application API documentation

using-mobile-extensions/places-extension-1/places-monitoring-extension/places-monitor-api-reference.md
Updated the Places Monitor iOS API thats been released for V 1.0.0
=> Places monitor API update

using-mobile-extensions/adobe-target-vec/README.md
@rekrishn Can you please review and merge?
=> Updated Adobe Target VEC Documentation and broken links

using-mobile-extensions/mobile-core/identity/identity-api-reference.md
Removed adidEnabled reference as this flag is not supported in v5.
=> Identity small fix - removed adidEnabled reference

using-mobile-extensions/mobile-core/rules-engine.md
- support added with fix for AMSDK-8028
=> Add timestampz info to rules-engine.md

using-mobile-extensions/adobe-target-vec.md
1. Added deeplink handling code.
2. Some minor formatting changes
@rekrishn Please review and merge.
=> Minor Changes for VEC Sample Code and some code formatting

release-notes.md
=> Update release notes with latest adobe target release

using-mobile-extensions/adobe-target-vec.md
Small fix where ObjC code was copied in swift section.
=> ObjC code replaced with Swift Code

using-mobile-extensions/adobe-analytics/README.md
Fixed typo that imports from wrong library.
=> Updated readme

release-notes.md
Also improved wording on some previous analytics release notes.
=> Update release notes Audience 2.0.1

release-notes.md
- Update Release Notes for iOS Identity v2.1.2
=> Update release notes for Oct 3 release

using-mobile-extensions/adobe-audience-manager/audience-manager-api-reference.md
Updating Audience docs based on AMSDK-8716.
=> [AMSDK-8744] Update audience docs

beta/adobe-places.md
=> Places changes

release-notes.md, using-mobile-extensions/mobile-core/identity/identity-api-reference.md
- Update release notes for Identity iOS v2.1.3 release
- Updated Identity API reference page to reflect the changes
=> Update release notes for Identity iOS v2.1.3 release

using-mobile-extensions/adobe-campaign-standard/README.md, using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-api-reference.md, using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-event-reference.md
- doc cleanup and fixing of errors
- try to improve doc wording
- add code samples
- add usage of collectMessageInfo API
=> [AMSDK-8766] ACS doc review

getting-started/create-a-mobile-property.md
We removed the https setting from the doc, since we only allow secure now. Need to remove it from the doc as well.
=> Remove https reference from doc

SUMMARY.md, resources/troubleshooting-guides/README.md
This PR contains the changes in Summary.md to include new document.
=> Campaign Push Notifications troubleshooting document

getting-started/create-a-mobile-property.md
Changes to 'Publish the configuration' section to make it more clear.
=> Changes to 'Publish the configuration' section

getting-started/get-the-sdk.md
Few updates to make steps for clear
=> Few updates to make steps for clear

using-mobile-extensions/adobe-target/target-api-reference.md
=> Target doc fixes

resources/user-guides/attach-data.md
Also shorten Target attach data section names.
=> Fix attach data links, add warning regarding VEC

release-notes.md, using-mobile-extensions/mobile-core/mobile-core-release-notes.md
Update release notes for Feb 18 release:
- Identity iOS v2.2.0
=> Update release-notes.md for Feb 18 release

using-mobile-extensions/mobile-core/identity/identity-api-reference.md
=> [AMSDK-9491] Clean up the table of contents for Identity API reference Doc

getting-started/enable-debug-logging.md, getting-started/enable-lifecycle-metrics.md, getting-started/get-the-sdk.md, getting-started/initialize-the-sdk.md, using-mobile-extensions/adobe-analytics/README.md, using-mobile-extensions/adobe-analytics/analytics-api-reference.md, using-mobile-extensions/adobe-analytics/product-variable.md, using-mobile-extensions/mobile-core/configuration/README.md, using-mobile-extensions/mobile-core/configuration/configuration-api-reference.md, using-mobile-extensions/mobile-core/identity/README.md, using-mobile-extensions/mobile-core/identity/identity-api-reference.md, using-mobile-extensions/mobile-core/lifecycle/README.md, using-mobile-extensions/mobile-core/lifecycle/lifecycle-api-reference.md, using-mobile-extensions/mobile-core/mobile-core-api-reference.md, using-mobile-extensions/mobile-core/signals/README.md
also includes some react native improvements
=> Flutter docs core and analytics

release-notes.md, using-mobile-extensions/mobile-core/mobile-core-release-notes.md
[AMSDK-9547] Updating the release notes for Identity v2.2.1 and Core v2.5.1
=> [AMSDK-9547] Updating the release notes for Identity v2.2.1 and Core v2.5.1

resources/adobe-experience-platform-mini-programs-sdk/faq.md
Answer the frequently asked questions
=> new created file

using-mobile-extensions/adobe-analytics/analytics-api-reference.md, using-mobile-extensions/mobile-core/mobile-core-api-reference.md
* Added syntax for React, Cordova, Flutter code snippets.
* Renamed section names with API names and ordered it alphabetically for sorted table of contents on the right.
* Added param description for the APIs
* Cleanup
=> Analytics doc gap fixes

getting-started/get-the-sdk.md, using-mobile-extensions/mobile-core/configuration/README.md, using-mobile-extensions/mobile-core/configuration/configuration-api-reference.md, using-mobile-extensions/mobile-core/identity/README.md, using-mobile-extensions/mobile-core/identity/identity-api-reference.md, using-mobile-extensions/mobile-core/lifecycle/README.md, using-mobile-extensions/mobile-core/lifecycle/lifecycle-api-reference.md, using-mobile-extensions/mobile-core/mobile-core-api-reference.md, using-mobile-extensions/mobile-core/signals/README.md, using-mobile-extensions/mobile-core/signals/signal-api-reference.md
Covers ACPCore, ACPIdentity, ACPLifecycle, and ACPSignal for Xamarin.
=> Add Xamarin ACPCore docs

using-mobile-extensions/adobe-analytics/analytics-api-reference.md, using-mobile-extensions/adobe-media-analytics/README.md
left over changes from PR: https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/pull/2
=> Sample code snippet improvements for Analytics

using-mobile-extensions/mobile-core/lifecycle/README.md
Minor edits Adobe-Marketing-Cloud/aep-sdks-documentation#334
=> Revert "Update formatting for readability"

using-mobile-extensions/adobe-places.md
Updating docs for react native places and places monitor
=> Adding RN places and places monitor

release-notes.md, using-mobile-extensions/adobe-audience-manager/adobe-audience-manager-release-notes.md, using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md
update release notes for Android Media 2.0.1  and Audience 1.0.2
=> update release notes for Android Media 2.0.1  and Audience 1.0.2

release-notes.md, using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md
Update release note for Media iOS 2.1.1 and react-native-acpmedia 2.0.1
=> Update release note for Media iOS 2.1.1 and react-native-acpmedia 2.0.1

release-notes.md, using-mobile-extensions/adobe-analytics/adobe-analytics-release-notes.md
Update release note for Android Analytics 1.2.5
=> Update release note for Android Analytics 1.2.5

release-notes.md, using-mobile-extensions/adobe-campaign-standard/README.md, using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-event-reference.md, using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-release-notes.md
release notes and enhancement information for ACS Android 1.0.7 and iOS 1.0.6.
=> add release notes and information for the latest ACS extension release

using-mobile-extensions/adobe-campaign-standard/README.md, using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-event-reference.md, using-mobile-extensions/adobe-campaignclassic/README.md, using-mobile-extensions/adobe-target/README.md, using-mobile-extensions/adobe-target/target-event-reference.md
- also some minor updates for acs and target event reference pages
=> update data types for target, acs, and acc configuration keys

beta/experience-platform-extension/tutorials/tutorial-4-rules-xdm-events.md
DateTime should be used instead of String.
=> Updates for assignment 4

beta/experience-platform-extension/tutorials/tutorial-1-edge-extension-setup.md
Update Mobile Core documentation link
=> Update Mobile Core documentation link in tutorial 1

using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md
Updated release notes for Media Analytics. Added React native release 2.2.0.
=> Updated release notes for Media Analytics.

using-mobile-extensions/adobe-analytics/README.md
replace docs.adobe.com and helpx.adobe.com URLs with their experienceleague.adobe.com URLs
=> update URLs to Adobe docs

release-notes.md, using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md
Update release note for Media releases
=> Update release note for Media releases

SUMMARY.md, release-notes.md, resources/privacy-and-gdpr.md, using-mobile-extensions/adobe-edge-consent/edge-consent-api-reference.md, using-mobile-extensions/adobe-edge-consent/edge-consent-release-notes.md
=> [AMSDK-11051] Consent API Ref & GDPR update

using-mobile-extensions/adobe-edge-identity/edge-identity-api-reference.md, using-mobile-extensions/mobile-core/mobile-core-api-reference.md
Add Edge Identity API Reference for all public APIs and classes. Adds resetIdentities API to Mobile Core API reference page.
=> Add Edge Identity API Reference

api-change-log.md
• Added missing APIs
• Replaced deprecated v5 APIs
=> Updated changelog for Target APIs 4.x -> v5 2.x

api-change-log.md
Removal of some more deprecated methods in Target API changelog
=> More changelog fixes

using-mobile-extensions/offer-decisioning/README.md, using-mobile-extensions/offer-decisioning/api-reference.md
• Updated Public Classes section with enhancements provided in v1.1.0
• Added a section for limitations with edge delivery e.g. Offer frequency capping (refer to [PLAT-98916](https://jira.corp.adobe.com/browse/PLAT-98916))
=> Doc updates for latest Offer release v1.1.0

using-mobile-extensions/adobe-campaign-standard/README.md, using-mobile-extensions/adobe-campaignclassic/README.md
Fixed the broken links in the Campaign Documentation.
=> Campaign: Fixed the broken Links

using-mobile-extensions/adobe-analytics/README.md, using-mobile-extensions/adobe-analytics/analytics-api-reference.md, using-mobile-extensions/adobe-analytics/migration.md
Fix links and format issues for Analytics Doc
=> Fix links and format issues  for Analytics Doc

release-notes/README.md, using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md, using-mobile-extensions/adobe-media-analytics/media-api-reference.md
Add release note for AEPMedia Android  2.1.2  and iOS 3.0.1
=> Add release note for AEPMedia Android  2.1.2  and iOS 3.0.1

using-mobile-extensions/adobe-analytics/adobe-analytics-release-notes.md, using-mobile-extensions/adobe-audience-manager/adobe-audience-manager-release-notes.md, using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md
Update release notes for Analytics, Audience and Media
=> Update release notes for Analytics, Audience and Media

release-notes/README.md, using-mobile-extensions/adobe-analytics/adobe-analytics-release-notes.md
Release notes for July 21, 2021
- iOS Analytics v2.5.1
- Android Analytics v1.2.7
=> Release notes for Analytics July 21 2021

using-mobile-extensions/adobe-analytics-mobile-services/README.md
Updated the document for Android push tracking in Mobile services SDK.
=> Mobile services Android Push tracking update.

release-notes/README.md, using-mobile-extensions/adobe-target/adobe-target-release-notes.md
Updated release notes with details on the fix for MOB-14886/ TNT-40395
=> Updated release notes for Target v3.1.0

release-notes/README.md, using-mobile-extensions/adobe-target/adobe-target-release-notes.md
=> Target v1.2.8 release notes

release-notes/README.md, using-mobile-extensions/adobe-media-analytics/adobe-media-release-notes.md
update release note for iOS ACPMedia 2.3.2
=> update release note for iOS ACPMedia 2.3.2

beta/project-griffon/troubleshoot-project-griffon.md, foundation-extensions/adobe-experience-platform-assurance/README.md
With regards to the feedback on https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/pull/676
=> Implement review feedback for Assurance

foundation-extensions/identity-for-edge-network/README.md, foundation-extensions/identity-for-edge-network/api-reference.md
Update Edge Identity api-reference and readme
AMSDK-11588
=> Update Edge Identity api-reference and readme

foundation-extensions/mobile-core/configuration/README.md, foundation-extensions/mobile-core/configuration/configuration-api-reference.md
Adds public documentation for the new public API `clearUpdatedConfiguration()` in AEPCore
=> clearUpdatedConfiguration() API Addition

foundation-extensions/profile/profile-api-references.md
- https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/pull/691#discussion_r804001432
- https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/pull/691#discussion_r804007594
Address above review comments in a new PR.
=> Update Profile docs (part II)

foundation-extensions/consent-for-edge-network/release-notes-1.md, foundation-extensions/experience-platform-extension/release-notes.md, foundation-extensions/mobile-core/mobile-core-release-notes.md, release-notes/README.md
Release notes for:
- Android Mobile Core 1.10.1
- Android Lifecycle 1.1.1
- Android Edge 1.3.1
- Android Consent 1.0.1
=> Release notes for Android Core 1.10.1, Lifecycle 1.1.1, Edge 1.3.1, and Consent 1.0.1

foundation-extensions/consent-for-edge-network/api-reference.md, resources/privacy-and-gdpr.md
https://jira.corp.adobe.com/browse/PLAT-119724
=> PLAT-119724 - Remove references to opt-back-in not being supported - READY

using-mobile-extensions/adobe-analytics/product-variable.md
fix tab layout and remove commas for &&products
=> fix tab layout

using-mobile-extensions/adobe-campaignclassic/README.md, using-mobile-extensions/adobe-campaignclassic/adobe-campaignclassic-api-reference.md, using-mobile-extensions/adobe-campaignclassic/adobe-campaignclassic-event-reference.md
Updates based on the doc guidelines
=> [MOB-15255] ACC doc updates

foundation-extensions/experience-platform-extension/edge-network-api-reference.md
=> Delete the extra endtab

foundation-extensions/mobile-core/mobile-core-release-notes.md, release-notes/README.md
Adding release notes for Android Mobile SDK Core v1.11.0 and Identity v1.3.1
=> Release notes for Android Core 1.11.0 and Identity 1.3.1

using-mobile-extensions/adobe-analytics/product-variable.md
Fixing syntax for product variable examples.
=> Fixing syntax for product variable examples.

beta/iam/setup-sdk.md
- use correct maven snapshot name and add optimize snapshot dependency
=> update android messaging sdk setup info

release-notes/README.md, using-mobile-extensions/adobe-journey-optimizer-decisioning/release-notes.md
- Updates to extension release notes based on feedback from Chetan
- Data Collection UI extension info
=> Optimize release notes

foundation-extensions/mobile-core/mobile-core-release-notes.md, release-notes/README.md, using-mobile-extensions/adobe-analytics/adobe-analytics-release-notes.md
Adding release notes for iOS ACPCore 2.9.6 and iOS ACPAnalytics 2.5.4.
=> Release notes for ACPCore 2.9.6 and ACPAnalytics 2.5.4

foundation-extensions/mobile-core/mobile-core-release-notes.md, release-notes/README.md
Release notes for Android Core 1.11.3
=> Release notes for Android Core 1.11.3

release-notes/README.md, using-mobile-extensions/adobe-target/adobe-target-release-notes.md
Release details:
Target iOS SDK v3.3.0
Target Android SDK v1.4.0
Adobe Target extension (Experience Platform Data Collection UI) v2.5.0
=> Added release notes for Adobe Target SDK release.

foundation-extensions/identity-for-edge-network/api-reference.md
Update typo in updateIdentities API example
=> Update typo in updateIdentities API example

release-notes/README.md
This PR adds the Edge Bridge release notes for iOS and Android
=> Add Edge Bridge release notes for iOS and Android

release-notes/README.md
This PR updates the Edge Bridge extension release description
=> Update Edge Bridge release description

release-notes/README.md, resources/upgrading-to-aep/current-sdk-versions.md
Add Flutter Edge Extensions release notes and update current sdk versions page.
=> Add Flutter Edge Extensions release notes and update current sdk versions page.

release-notes/README.md
Fix a format issue in release note
=> Fix a format issue in release note

foundation-extensions/mobile-core/mobile-core-release-notes.md, release-notes/README.md
Release notes for AEPCore 3.7.3
=> Release notes for AEPCore 3.7.3
